// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB64VpF8I0Dx1A-KTEBUh4EmHkLRAq4p-M',
    appId: '1:863128092138:web:3a27ac28bb525d27d74693',
    messagingSenderId: '863128092138',
    projectId: 'moviles-dc5c1',
    authDomain: 'moviles-dc5c1.firebaseapp.com',
    storageBucket: 'moviles-dc5c1.appspot.com',
    measurementId: 'G-NXHE2PELP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0Z8SGwD-MQ2tjdY-u-kgESXAfPg-4Mk',
    appId: '1:863128092138:android:20f4a4b5b0c08259d74693',
    messagingSenderId: '863128092138',
    projectId: 'moviles-dc5c1',
    storageBucket: 'moviles-dc5c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TJ9k6nLBUVunXSE-F7E_eVAc_syoKUA',
    appId: '1:863128092138:ios:607bd1c796bee6eed74693',
    messagingSenderId: '863128092138',
    projectId: 'moviles-dc5c1',
    storageBucket: 'moviles-dc5c1.appspot.com',
    iosBundleId: 'com.example.pmsn2024b',
  );
}
